name: cesu

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 8,20 * * *'  # 每12小时运行一次，可以根据需求调整

jobs:
  ip-speed-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl bash

    - name: Check if script exists
      run: |
        if [ ! -f cesu.sh ]; then
          echo "Error: cesu.sh not found!"
          exit 1
        fi

    - name: Run shell script
      run: |
        chmod +x cesu.sh
        ./cesu.sh

    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add FDIP/*.* CloudflareST/*.*
        git commit --allow-empty -m "Add fdIPs with speed" || echo "No changes to commit"
        git push
